In [7]:
import pandas as pd
import numpy as np

import pylab as pl
from sklearn.neighbors import KNeighborsClassifier

In [8]:
df_age_19=pd.read_csv('Data/AgeData/df_age_19.csv',index_col=0)
df_age_20=pd.read_csv('Data/AgeData/df_age_20.csv',index_col=0)
df_age_21=pd.read_csv('Data/AgeData/df_age_21.csv',index_col=0)
df_age_22=pd.read_csv('Data/AgeData/df_age_22.csv',index_col=0)
df_age_23=pd.read_csv('Data/AgeData/df_age_23.csv',index_col=0)
df_age_24=pd.read_csv('Data/AgeData/df_age_24.csv',index_col=0)
df_age_25=pd.read_csv('Data/AgeData/df_age_25.csv',index_col=0)
df_age_26=pd.read_csv('Data/AgeData/df_age_26.csv',index_col=0)
df_age_27=pd.read_csv('Data/AgeData/df_age_27.csv',index_col=0)
df_age_28=pd.read_csv('Data/AgeData/df_age_28.csv',index_col=0)
df_age_29=pd.read_csv('Data/AgeData/df_age_29.csv',index_col=0)

df_age_30=pd.read_csv('Data/AgeData/df_age_30.csv',index_col=0)
df_age_31=pd.read_csv('Data/AgeData/df_age_31.csv',index_col=0)
df_age_32=pd.read_csv('Data/AgeData/df_age_32.csv',index_col=0)
df_age_33=pd.read_csv('Data/AgeData/df_age_33.csv',index_col=0)
df_age_34=pd.read_csv('Data/AgeData/df_age_34.csv',index_col=0)
df_age_35=pd.read_csv('Data/AgeData/df_age_35.csv',index_col=0)
df_age_36=pd.read_csv('Data/AgeData/df_age_36.csv',index_col=0)
df_age_37=pd.read_csv('Data/AgeData/df_age_37.csv',index_col=0)
df_age_38=pd.read_csv('Data/AgeData/df_age_38.csv',index_col=0)
df_age_39=pd.read_csv('Data/AgeData/df_age_39.csv',index_col=0)

In [9]:
dfplayer1996=pd.read_csv('Data/draft_year_player/dfplayer1996.csv')
dfplayer1997=pd.read_csv('Data/draft_year_player/dfplayer1997.csv')
dfplayer1998=pd.read_csv('Data/draft_year_player/dfplayer1998.csv')
dfplayer1999=pd.read_csv('Data/draft_year_player/dfplayer1999.csv')

dfplayer2000=pd.read_csv('Data/draft_year_player/dfplayer2000.csv')
dfplayer2001=pd.read_csv('Data/draft_year_player/dfplayer2001.csv')
dfplayer2002=pd.read_csv('Data/draft_year_player/dfplayer2002.csv')
dfplayer2003=pd.read_csv('Data/draft_year_player/dfplayer2003.csv')
dfplayer2004=pd.read_csv('Data/draft_year_player/dfplayer2004.csv')

dfplayer2005=pd.read_csv('Data/draft_year_player/dfplayer2005.csv')
dfplayer2006=pd.read_csv('Data/draft_year_player/dfplayer2006.csv')
dfplayer2007=pd.read_csv('Data/draft_year_player/dfplayer2007.csv')
dfplayer2008=pd.read_csv('Data/draft_year_player/dfplayer2008.csv')
dfplayer2009=pd.read_csv('Data/draft_year_player/dfplayer2009.csv')

dfplayer2010=pd.read_csv('Data/draft_year_player/dfplayer2010.csv')
dfplayer2011=pd.read_csv('Data/draft_year_player/dfplayer2011.csv')
dfplayer2012=pd.read_csv('Data/draft_year_player/dfplayer2012.csv')
dfplayer2013=pd.read_csv('Data/draft_year_player/dfplayer2013.csv')
dfplayer2014=pd.read_csv('Data/draft_year_player/dfplayer2014.csv')

dfplayer2015=pd.read_csv('Data/draft_year_player/dfplayer2015.csv')

In [10]:
namePlayer=[]
for elem in dfplayer1996['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer1996['name']=namePlayer

del dfplayer1996['Unnamed: 0']
del dfplayer1996['url']
del dfplayer1996['draft']
del dfplayer1996['shot']
del dfplayer1996['pos']


namePlayer=[]
for elem in dfplayer1997['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer1997['name']=namePlayer

del dfplayer1997['Unnamed: 0']
del dfplayer1997['url']
del dfplayer1997['draft']
del dfplayer1997['shot']
del dfplayer1997['pos']

namePlayer=[]
for elem in dfplayer1998['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer1998['name']=namePlayer

del dfplayer1998['Unnamed: 0']
del dfplayer1998['url']
del dfplayer1998['draft']
del dfplayer1998['shot']
del dfplayer1998['pos']

namePlayer=[]
for elem in dfplayer1999['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer1999['name']=namePlayer

del dfplayer1999['Unnamed: 0']
del dfplayer1999['url']
del dfplayer1999['draft']
del dfplayer1999['shot']
del dfplayer1999['pos']

namePlayer=[]
for elem in dfplayer2000['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2000['name']=namePlayer

del dfplayer2000['Unnamed: 0']
del dfplayer2000['url']
del dfplayer2000['draft']
del dfplayer2000['shot']
del dfplayer2000['pos']

namePlayer=[]
for elem in dfplayer2001['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2001['name']=namePlayer

del dfplayer2001['Unnamed: 0']
del dfplayer2001['url']
del dfplayer2001['draft']
del dfplayer2001['shot']
del dfplayer2001['pos']

namePlayer=[]
for elem in dfplayer2002['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2002['name']=namePlayer

del dfplayer2002['Unnamed: 0']
del dfplayer2002['url']
del dfplayer2002['draft']
del dfplayer2002['shot']
del dfplayer2002['pos']

namePlayer=[]
for elem in dfplayer2003['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2003['name']=namePlayer

del dfplayer2003['Unnamed: 0']
del dfplayer2003['url']
del dfplayer2003['draft']
del dfplayer2003['shot']
del dfplayer2003['pos']

namePlayer=[]
for elem in dfplayer2004['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2004['name']=namePlayer

del dfplayer2004['Unnamed: 0']
del dfplayer2004['url']
del dfplayer2004['draft']
del dfplayer2004['shot']
del dfplayer2004['pos']

namePlayer=[]
for elem in dfplayer2005['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2005['name']=namePlayer

del dfplayer2005['Unnamed: 0']
del dfplayer2005['url']
del dfplayer2005['draft']
del dfplayer2005['shot']
del dfplayer2005['pos']

namePlayer=[]
for elem in dfplayer2006['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2006['name']=namePlayer

del dfplayer2006['Unnamed: 0']
del dfplayer2006['url']
del dfplayer2006['draft']
del dfplayer2006['shot']
del dfplayer2006['pos']

namePlayer=[]
for elem in dfplayer2007['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2007['name']=namePlayer

del dfplayer2007['Unnamed: 0']
del dfplayer2007['url']
del dfplayer2007['draft']
del dfplayer2007['shot']
del dfplayer2007['pos']

namePlayer=[]
for elem in dfplayer2008['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2008['name']=namePlayer

del dfplayer2008['Unnamed: 0']
del dfplayer2008['url']
del dfplayer2008['draft']
del dfplayer2008['shot']
del dfplayer2008['pos']

namePlayer=[]
for elem in dfplayer2009['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2009['name']=namePlayer

del dfplayer2009['Unnamed: 0']
del dfplayer2009['url']
del dfplayer2009['draft']
del dfplayer2009['shot']
del dfplayer2009['pos']

namePlayer=[]
for elem in dfplayer2010['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2010['name']=namePlayer

del dfplayer2010['Unnamed: 0']
del dfplayer2010['url']
del dfplayer2010['draft']
del dfplayer2010['shot']
del dfplayer2010['pos']

namePlayer=[]
for elem in dfplayer2011['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2011['name']=namePlayer

del dfplayer2011['Unnamed: 0']
del dfplayer2011['url']
del dfplayer2011['draft']
del dfplayer2011['shot']
del dfplayer2011['pos']

namePlayer=[]
for elem in dfplayer2012['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2012['name']=namePlayer

del dfplayer2012['Unnamed: 0']
del dfplayer2012['url']
del dfplayer2012['draft']
del dfplayer2012['shot']
del dfplayer2012['pos']

namePlayer=[]
for elem in dfplayer2013['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2013['name']=namePlayer

del dfplayer2013['Unnamed: 0']
del dfplayer2013['url']
del dfplayer2013['draft']
del dfplayer2013['shot']
del dfplayer2013['pos']

namePlayer=[]
for elem in dfplayer2014['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2014['name']=namePlayer

del dfplayer2014['Unnamed: 0']
del dfplayer2014['url']
del dfplayer2014['draft']
del dfplayer2014['shot']
del dfplayer2014['pos']

namePlayer=[]
for elem in dfplayer2015['url']:
    namePlayer.append(elem[11:-5])
    
dfplayer2015['name']=namePlayer

del dfplayer2015['Unnamed: 0']
del dfplayer2015['url']
del dfplayer2015['draft']
del dfplayer2015['shot']
del dfplayer2015['pos']

In [11]:
fundam = [dfplayer1996,dfplayer1997,dfplayer1998,dfplayer1999,dfplayer2000,dfplayer2001,dfplayer2002,
dfplayer2003,dfplayer2004,dfplayer2005,dfplayer2006,dfplayer2007,dfplayer2008,dfplayer2009,dfplayer2010,
dfplayer2011,dfplayer2012,dfplayer2013,dfplayer2014,dfplayer2015]



df_all_fundam = pd.concat(fundam)

In [13]:
df_all_fundam

           name height weight
0     phillch02    190    219
1     zyuzian01    185    208
2     dumonjp01    185    205
3     volchal01    188    204
4     jackmri01    188    214
5     deverbo01    188    195
6     rasmuer01    185    215
7     aitkejo01    193    230
8     saleiru01    185    212
9      wardla01    190    210
10    fochtda01    198    234
11    holdejo01    183    190
12    morride01    183    200
13    reasoma01    185    197
14    zubruda01    196    225
15    larocma01    193    218
16    svejkja01    185    193
17    higgima01    188    190
18    descoma01    190    216
19    nilsoma01    188    189
20    sturmma01    183    196
21    brierda01    175    174
22    ratchpe01    185    185
23    wallije01    188    190
24    saricco01    193    207
25    skrbepa01    190    217
26    lacouda01    188    215
27    greenjo01    193    225
28    royerre01    188    200
29     hajtch01    190    206
...         ...    ...    ...
4083  chukaiv01    188    190
4084  kallger01    180    157
4085  huskaad01    190    189
4086  korosni01    185    195
4087  lorenst01    188    191
4088  reddech01    190    219
4089  fedotiv01    198    191
4090  nutivma01    183    174
4091   velama01    183    204
4092  olhavgu01    198    213
4093   sheapa02    178    186
4094  kupskjo01    196    210
4095    royma04    183    200
4096  beckeja01    190    188
4097  bruceri01    198    205
4098  pavlyni01    201    200
4099   nikusa01    183    176
4100  daccojo01    188    197
4101  marshad01    183    160
4102  bouragu01    180    184
4103  hansspe01    185    187
4104  gennama01    188    187
4105  sadekja01    185    185
4106  smithev01    198    174
4107  bednary01    190    179
4108  addisje01    180    182
4109  svobomi01    190    176
4110  paigizi01    198    209
4111  olsonta01    188    174
4112  dahlsjo01    180    189

[4113 rows x 3 columns]

In [14]:
df_all_fundam=df_all_fundam.reset_index(drop=True)

In [15]:
df_all_fundam = df_all_fundam[df_all_fundam.height!= 'ml>']

In [16]:
df_all_fundam=df_all_fundam.reset_index(drop=True)
weight_all=df_all_fundam['weight']
height_all=df_all_fundam['height']

In [17]:
df_all_fundam[['weight','height']]=df_all_fundam[['weight','height']].astype(float)

In [18]:
df_all_fundam

           name  height  weight
0     phillch02   190.0   219.0
1     zyuzian01   185.0   208.0
2     dumonjp01   185.0   205.0
3     volchal01   188.0   204.0
4     jackmri01   188.0   214.0
5     deverbo01   188.0   195.0
6     rasmuer01   185.0   215.0
7     aitkejo01   193.0   230.0
8     saleiru01   185.0   212.0
9      wardla01   190.0   210.0
10    fochtda01   198.0   234.0
11    holdejo01   183.0   190.0
12    morride01   183.0   200.0
13    reasoma01   185.0   197.0
14    zubruda01   196.0   225.0
15    larocma01   193.0   218.0
16    svejkja01   185.0   193.0
17    higgima01   188.0   190.0
18    descoma01   190.0   216.0
19    nilsoma01   188.0   189.0
20    sturmma01   183.0   196.0
21    brierda01   175.0   174.0
22    ratchpe01   185.0   185.0
23    wallije01   188.0   190.0
24    saricco01   193.0   207.0
25    skrbepa01   190.0   217.0
26    lacouda01   188.0   215.0
27    greenjo01   193.0   225.0
28    royerre01   188.0   200.0
29     hajtch01   190.0   206.0
...         ...     ...     ...
2490  chukaiv01   188.0   190.0
2491  kallger01   180.0   157.0
2492  huskaad01   190.0   189.0
2493  korosni01   185.0   195.0
2494  lorenst01   188.0   191.0
2495  reddech01   190.0   219.0
2496  fedotiv01   198.0   191.0
2497  nutivma01   183.0   174.0
2498   velama01   183.0   204.0
2499  olhavgu01   198.0   213.0
2500   sheapa02   178.0   186.0
2501  kupskjo01   196.0   210.0
2502    royma04   183.0   200.0
2503  beckeja01   190.0   188.0
2504  bruceri01   198.0   205.0
2505  pavlyni01   201.0   200.0
2506   nikusa01   183.0   176.0
2507  daccojo01   188.0   197.0
2508  marshad01   183.0   160.0
2509  bouragu01   180.0   184.0
2510  hansspe01   185.0   187.0
2511  gennama01   188.0   187.0
2512  sadekja01   185.0   185.0
2513  smithev01   198.0   174.0
2514  bednary01   190.0   179.0
2515  addisje01   180.0   182.0
2516  svobomi01   190.0   176.0
2517  paigizi01   198.0   209.0
2518  olsonta01   188.0   174.0
2519  dahlsjo01   180.0   189.0

[2520 rows x 3 columns]

In [15]:
frames = [df_age_19, df_age_20, df_age_21,df_age_22,df_age_23,df_age_24,df_age_25,df_age_26,df_age_27,df_age_28,
         df_age_29,df_age_30,df_age_31,df_age_32,df_age_33,df_age_34,df_age_35,df_age_36,df_age_37,df_age_38,df_age_39]
df_all = pd.concat(frames)

In [16]:
df_all=df_all.reset_index(drop=True)

In [17]:
del df_all['age_x']

In [18]:
df_all['goals_all']=df_all['goals_ev']+df_all['goals_pp']+df_all['goals_sh']

In [19]:
result=df_all.sort(['name', 'age_y'], ascending=[0, 1])

/Users/takehiromatsuzawa/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [20]:
result.head()

,TOT,age_y,assists_ev,assists_pp,assists_sh,blocks,corsi_against,corsi_for,corsi_pct,corsi_rel_pct,...,shot_pct,shot_pct.1,shots_attempted,shots_attempted.1,takeaways,time_on_ice_avg,uniqueseason,zs_defense_pct,zs_offense_pct,goals_all
5478,CHI,30.0,2.0,1.0,0.0,35.0,312.0,275.0,46.8,-7.0,...,5.9,5.9,68.0,NaN,6.0,14.58,1,54.2,45.8,2.0
416,MIN,20.0,2.0,0.0,0.0,2.0,73.0,40.0,35.4,-8.8,...,0.0,0.0,16.0,16.0,2.0,11.02,1,48.3,51.7,0.0
894,MIN,21.0,1.0,0.0,0.0,5.0,216.0,183.0,45.9,-6.6,...,11.8,11.8,58.0,58.0,4.0,11.16,1,58.4,41.6,4.0
1516,MIN,22.0,0.0,1.0,0.0,11.0,259.0,198.0,43.3,-5.0,...,10.0,10.0,68.0,68.0,9.0,12.59,1,42.7,57.3,4.0
2221,MIN,23.0,5.0,0.0,0.0,13.0,547.0,641.0,54.0,2.6,...,16.9,16.9,193.0,193.0,21.0,15.04,1,46.2,53.8,21.0

In [21]:
result=result.reset_index(drop=True)

In [22]:
result['goals_all']=result['goals_all']/result['games_played']

In [23]:
goals_all_data=list(result['goals_all'])

In [24]:
goals_all_data.pop(0)
goals_all_data.append(0)

In [25]:
result['goals_all']=goals_all_data

In [26]:
df_all=result.groupby("name").apply(lambda x: x.iloc[:-1]).reset_index(drop=True)

In [27]:
df_all = pd.merge(df_all, df_all_fundam, on='name')

In [28]:
df_all=df_all.drop_duplicates()

In [29]:
df_all.head()

,TOT,age_y,assists_ev,assists_pp,assists_sh,blocks,corsi_against,corsi_for,corsi_pct,corsi_rel_pct,...,shots_attempted,shots_attempted.1,takeaways,time_on_ice_avg,uniqueseason,zs_defense_pct,zs_offense_pct,goals_all,height,weight
0,DET,20.0,0.0,0.0,0.0,0.0,18.0,19.0,51.4,-10.0,...,8.0,8.0,1.0,12.13,1,40.0,60.0,0.000000,188.0,218.0
1,DET,21.0,0.0,0.0,0.0,0.0,9.0,22.0,71.0,14.6,...,7.0,7.0,0.0,9.18,1,33.3,66.7,0.060000,188.0,218.0
2,DET,22.0,3.0,0.0,0.0,20.0,376.0,409.0,52.1,-2.2,...,141.0,141.0,7.0,10.35,1,33.7,66.3,0.094595,188.0,218.0
3,DET,23.0,11.0,0.0,1.0,39.0,628.0,765.0,54.9,-0.4,...,226.0,226.0,17.0,12.18,1,41.2,58.8,0.098765,188.0,218.0
4,DET,24.0,14.0,0.0,0.0,42.0,698.0,794.0,53.2,-3.2,...,196.0,196.0,16.0,12.19,1,40.7,59.3,0.208333,188.0,218.0

In [30]:
#df_all['goals_all']=df_all['goals_all']
df_all['goals_ev']=df_all['goals_ev']/df_all['games_played']
df_all['goals_pp']=df_all['goals_pp']/df_all['games_played']
df_all['goals_sh']=df_all['goals_sh']/df_all['games_played']

df_all['assists_all']=df_all['assists_ev']+df_all['assists_pp']+df_all['assists_sh']
df_all['assists_all']=df_all['assists_all']/df_all['games_played']
df_all['assists_ev']=df_all['assists_ev']/df_all['games_played']
df_all['assists_pp']=df_all['assists_pp']/df_all['games_played']
df_all['assists_sh']=df_all['assists_sh']/df_all['games_played']

df_all['zs_offense_pct']=df_all['zs_offense_pct']/100.0
df_all['shot_pct']=df_all['shot_pct']/100.0
df_all['takeaways']=df_all['takeaways']/df_all['games_played']
df_all['hits']=df_all['hits']/df_all['games_played']

df_all['giveaways']=df_all['giveaways']/df_all['games_played']
df_all['blocks']=df_all['blocks']/df_all['games_played']

df_all['shots_attempted']=df_all['shots_attempted']/df_all['games_played']

In [31]:
df_all.head()

,TOT,age_y,assists_ev,assists_pp,assists_sh,blocks,corsi_against,corsi_for,corsi_pct,corsi_rel_pct,...,shots_attempted.1,takeaways,time_on_ice_avg,uniqueseason,zs_defense_pct,zs_offense_pct,goals_all,height,weight,assists_all
0,DET,20.0,0.000000,0.0,0.000000,0.000000,18.0,19.0,51.4,-10.0,...,8.0,0.500000,12.13,1,40.0,0.600,0.000000,188.0,218.0,0.000000
1,DET,21.0,0.000000,0.0,0.000000,0.000000,9.0,22.0,71.0,14.6,...,7.0,0.000000,9.18,1,33.3,0.667,0.060000,188.0,218.0,0.000000
2,DET,22.0,0.060000,0.0,0.000000,0.400000,376.0,409.0,52.1,-2.2,...,141.0,0.140000,10.35,1,33.7,0.663,0.094595,188.0,218.0,0.060000
3,DET,23.0,0.148649,0.0,0.013514,0.527027,628.0,765.0,54.9,-0.4,...,226.0,0.229730,12.18,1,41.2,0.588,0.098765,188.0,218.0,0.162162
4,DET,24.0,0.172840,0.0,0.000000,0.518519,698.0,794.0,53.2,-3.2,...,196.0,0.197531,12.19,1,40.7,0.593,0.208333,188.0,218.0,0.172840

In [32]:
df_all_nn=df_all[['goals_all','goals_ev','goals_pp','goals_sh','assists_ev','assists_pp','assists_sh','shots_attempted','age_y','blocks',
                 'giveaways','hits','shot_pct','shots_attempted','takeaways','zs_offense_pct','height','weight']]

In [33]:
df_all_nn.head()

,goals_all,goals_ev,goals_pp,goals_sh,assists_ev,assists_pp,assists_sh,shots_attempted,age_y,blocks,giveaways,hits,shot_pct,shots_attempted,takeaways,zs_offense_pct,height,weight
0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,4.000000,20.0,0.000000,0.00000,2.500000,0.000,4.000000,0.500000,0.600,188.0,218.0
1,0.060000,0.000000,0.0,0.0,0.000000,0.0,0.000000,3.500000,21.0,0.000000,0.50000,1.500000,0.000,3.500000,0.000000,0.667,188.0,218.0
2,0.094595,0.060000,0.0,0.0,0.060000,0.0,0.000000,2.820000,22.0,0.400000,0.14000,3.040000,0.038,2.820000,0.140000,0.663,188.0,218.0
3,0.098765,0.094595,0.0,0.0,0.148649,0.0,0.013514,3.054054,23.0,0.527027,0.27027,2.540541,0.054,3.054054,0.229730,0.588,188.0,218.0
4,0.208333,0.098765,0.0,0.0,0.172840,0.0,0.000000,2.419753,24.0,0.518519,0.17284,1.827160,0.066,2.419753,0.197531,0.593,188.0,218.0

In [34]:
cols_to_norm = ['goals_ev','goals_pp','goals_sh','assists_ev','assists_pp','assists_sh','shots_attempted','age_y','blocks','giveaways',
               'hits','shot_pct','shots_attempted','takeaways','zs_offense_pct','height','weight']
df_all_nn_2=df_all_nn[cols_to_norm].apply(lambda x: (x - x.mean()) / (x.max() - x.min()))

In [35]:
df_all_nn_2.head()

,goals_ev,goals_pp,goals_sh,assists_ev,assists_pp,assists_sh,shots_attempted,shots_attempted,age_y,blocks,giveaways,hits,shot_pct,shots_attempted,shots_attempted,takeaways,zs_offense_pct,height,weight
0,-0.108012,-0.032897,-0.008061,-0.177088,-0.062086,-0.020775,0.092108,0.092108,-0.290891,-0.203475,-0.136367,0.173870,-0.080549,0.092108,0.092108,0.079107,0.091405,0.047091,0.125788
1,-0.108012,-0.032897,-0.008061,-0.177088,-0.062086,-0.020775,0.046275,0.046275,-0.238260,-0.203475,0.030300,0.031013,-0.080549,0.046275,0.046275,-0.213862,0.158405,0.047091,0.125788
2,-0.048012,-0.032897,-0.008061,-0.117088,-0.062086,-0.020775,-0.016057,-0.016057,-0.185628,-0.091814,-0.089700,0.251013,-0.042549,-0.016057,-0.016057,-0.131830,0.154405,0.047091,0.125788
3,-0.013418,-0.032897,-0.008061,-0.028439,-0.062086,0.046792,0.005397,0.005397,-0.132997,-0.056354,-0.046277,0.179662,-0.026549,0.005397,0.005397,-0.079254,0.079405,0.047091,0.125788
4,-0.009247,-0.032897,-0.008061,-0.004248,-0.062086,-0.020775,-0.052746,-0.052746,-0.080365,-0.058730,-0.078754,0.077751,-0.014549,-0.052746,-0.052746,-0.098121,0.084405,0.047091,0.125788

In [36]:
df_all_nn_2['goals_all']=df_all_nn['goals_all']

In [37]:
df_all_nn_2['age_y'] = df_all_nn_2['age_y'].apply(lambda x: abs(x))

In [38]:
df_all_nn_2=df_all_nn_2.reset_index(drop=True)

In [39]:
import pandas as pd
import pylab as pl
from sklearn.neighbors import KNeighborsClassifier

In [40]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet

In [41]:
import statsmodels.api as sm

In [42]:

features = ['goals_pp','goals_ev','goals_sh','assists_ev','assists_pp','assists_sh','age_y',
               'hits','shots_attempted','takeaways','zs_offense_pct','weight','height']

alpha_val=[1e-8, 1e-6, 1e-5, 1e-4, 5e-4, 1e-3, 1e-2]
results_all_OLR=[]

result=[]
for k in range(0,100):
    test_idx = np.random.uniform(0, 1, len(df_all_nn_2)) <= 0.8
    train = df_all_nn_2[test_idx==True]
    test = df_all_nn_2[test_idx==False]

    train_goals_all=list(train['goals_all'])
    train_data=train[features].as_matrix()
    #train_data=np.array(train_data).tolist()
    test_data=test[features].as_matrix()
    #test_data=np.array(test_data).tolist()

    model=sm.OLS(train_goals_all,train_data).fit()
    
    #clfridge = Lasso(alpha=alphaval).fit(train_data,train_goals_all)

    preds = model.predict(test_data)
    test_goals_all=list(test['goals_all'])
    distance=0
    for i in range(len(preds)):
        if preds[i]<0:
            distance += pow((test_goals_all[i]), 2)
        else:    
            distance += pow((test_goals_all[i]-preds[i]), 2)


    result.append(distance)
    
    #results_all_OLR.append()
    
print sum(result)/(len(result)*len(preds))

0.0115497065885

In [43]:
min(preds)

-0.13329089133531993

In [44]:
max(preds)

0.54474462841527738

In [ ]:

features = ['goals_pp','goals_ev','goals_sh','assists_ev','assists_pp','assists_sh','age_y',
               'hits','shots_attempted','takeaways','zs_offense_pct','weight','height']
alpha_val=[1e-8, 1e-6, 1e-5, 1e-4, 5e-4, 1e-3, 1e-2]
results_all_ridge=[]

for alphaval in alpha_val:
    result=[]
    
    for k in range(0,20):
        test_idx = np.random.uniform(0, 1, len(df_all_nn_2)) <= 0.8
        train = df_all_nn_2[test_idx==True]
        test = df_all_nn_2[test_idx==False]

        train_goals_all=list(train['goals_all'])
        train_data=train[features].as_matrix()
        #train_data=np.array(train_data).tolist()
        test_data=test[features].as_matrix()
        #test_data=np.array(test_data).tolist()

        clfridge = Lasso(alpha=alphaval).fit(train_data,train_goals_all)

        preds = clfridge.predict(test_data)
        test_goals_all=list(test['goals_all'])
        distance=0
        for i in range(len(preds)):
            distance += pow((test_goals_all[i]-preds[i]), 2)

        
        result.append(distance)
    
    results_all_ridge.append([alphaval, sum(result)/(len(result)*len(preds))])
    
print results_all_ridge

[[1e-08, 0.0069457602250403132], [1e-06, 0.007061539523888145], [1e-05, 0.00695289397971517], [0.0001, 0.0070702326854998167], [0.0005, 0.0073255057066531357], [0.001, 0.0075630566575430507], [0.01, 0.015888183984150431]]

In [ ]:
results_df_ridge = pd.DataFrame(results_all_ridge, columns=["Penalty", "error"])

pl.plot(results_df_ridge.Penalty, results_df_ridge.error)
pl.title("Error with Increasing Penalty (Ridge)")
pl.xlabel('Penalty')
pl.ylabel('Error')
pl.show()

In [ ]:
results_df_ridge

In [423]:

features = ['goals_pp','goals_ev','goals_sh','assists_ev','assists_pp','assists_sh','age_y',
               'hits','shots_attempted','takeaways','zs_offense_pct','weight','height']
alpha_val=[1e-8, 1e-6, 1e-5, 1e-4, 5e-4, 1e-3, 1e-2]
#alpha_val=[1e-8]
results_all_lasso=[]
dict_coef={}
dict_coef_sum={}


for i in range(len(clflasso.coef_)):
    dict_coef[i]=0
    dict_coef_sum[i]=0
    
for alphaval in alpha_val:
    result=[]
    
    for k in range(0,100):
        test_idx = np.random.uniform(0, 1, len(df_all_nn_2)) <= 0.8
        train = df_all_nn_2[test_idx==True]
        test = df_all_nn_2[test_idx==False]

        train_goals_all=list(train['goals_all'])
        train_data=train[features].as_matrix()
        #train_data=np.array(train_data).tolist()
        test_data=test[features].as_matrix()
        #test_data=np.array(test_data).tolist()

        clflasso = Lasso(alpha=alphaval).fit(train_data,train_goals_all)
        coeffs=clflasso.coef_
        
        for elem in range(len(coeffs)):
            if coeffs[elem]==0:
                dict_coef[elem]=dict_coef[elem]+1
            dict_coef_sum[elem]=dict_coef_sum[elem]+coeffs[elem]/float(800)
            
        preds = clflasso.predict(test_data)
        test_goals_all=list(test['goals_all'])
        distance=0
        for i in range(len(preds)):
            distance += pow((test_goals_all[i]-preds[i]), 2)

        
        result.append(distance)
    
    results_all_lasso.append([alphaval, sum(result)/(len(result)*len(preds))])
    
print results_all_lasso

[[1e-08, 0.0071786626004433328], [1e-06, 0.0070957572852843789], [1e-05, 0.0069424989503693545], [0.0001, 0.0071890635598187641], [0.0005, 0.0069031835012439953], [0.001, 0.0074691859306673927], [0.01, 0.01586156798709859]]

In [415]:
train.columns

Index([u'goals_ev', u'goals_pp', u'goals_sh', u'assists_ev', u'assists_pp',
       u'assists_sh', u'shots_attempted', u'shots_attempted', u'age_y',
       u'blocks', u'giveaways', u'hits', u'shot_pct', u'shots_attempted',
       u'shots_attempted', u'takeaways', u'zs_offense_pct', u'height',
       u'weight', u'goals_all'],
      dtype='object')

In [411]:
len(features)

13

In [424]:
dict_coef_sum

{0: 0.4328643636315328,
 1: 0.35096775448022421,
 2: 0.079668221553781032,
 3: 0.035011446349379256,
 4: -0.0068223756012199058,
 5: -0.0068759302095574735,
 6: -0.0048746485310280623,
 7: -0.011930205863969314,
 8: 0.13297063809778828,
 9: 1.2013493290376866e-16,
 10: 4.0546755513925232e-18,
 11: 2.5004648502714092e-18,
 12: 0.086810096686060406,
 13: 0.021833196359791206,
 14: 0.0018922526014202362,
 15: -0.011403330958065111}

In [425]:
dict(zip(train[features].columns, dict_coef_sum.values()))

{'age_y': -0.0048746485310280623,
 'assists_ev': 0.035011446349379256,
 'assists_pp': -0.0068223756012199058,
 'assists_sh': -0.0068759302095574735,
 'goals_ev': 0.35096775448022421,
 'goals_pp': 0.4328643636315328,
 'goals_sh': 0.079668221553781032,
 'height': -0.011403330958065111,
 'hits': -0.011930205863969314,
 'shots_attempted': 2.5004648502714092e-18,
 'takeaways': 0.086810096686060406,
 'weight': 0.0018922526014202362,
 'zs_offense_pct': 0.021833196359791206}

In [419]:
dict_coef.values()

[0, 0, 0, 0, 0, 1, 1, 0, 0, 49, 85, 85, 0]

In [339]:
results_df_lasso = pd.DataFrame(results_all_lasso, columns=["Penalty", "error"])

pl.plot(results_df_lasso.Penalty, results_df_lasso.error)
pl.title("Error with Increasing Penalty (Lasso)")
pl.xlabel('Penalty')
pl.ylabel('Error')
pl.show()

In [340]:
results_df_lasso

        Penalty     error
0  1.000000e-08  0.006994
1  1.000000e-06  0.007124
2  1.000000e-05  0.007175
3  1.000000e-04  0.007429
4  5.000000e-04  0.006913
5  1.000000e-03  0.007375
6  1.000000e-02  0.016366

In [344]:
len(clflasso.coef_)

16

In [347]:
dict_coef={}
for i in range(len(clflasso.coef_)):
    dict_coef[i]=0

In [348]:
coeffs=clflasso.coef_

In [353]:

for elem in range(len(coeffs)):
    if coeffs[elem]==0:
        dict_coef[elem]=dict_coef[elem]+1

print dict_coef

{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 0, 9: 0, 10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1}